### ISSUE TITLE
Cant use text or voice chat after injecting 

### ISSUE THREAD

**Issue by kennyS-69420** [emilyinure/haven-tf2#21]
Voice and text chat are disabled after injecting for some reason.

**Comment by emilyinure** [comment]
thats odd, is everything else working?

**Comment by kennyS-69420** [comment]
ya everything else is working great

**Comment by emilyinure** [comment]
anything special about your system? windows ver?

**Comment by kennyS-69420** [comment]
Not really just Windows 11 Pro 22H2 22621.2506

**Comment by kennyS-69420** [comment]
figured it out I was being stupid new to tf2 lol
