### ISSUE TITLE
Why seperate the visuals (esp etc) from the aim bot etc

### ISSUE THREAD

**Issue by LocalSmail** [emilyinure/haven-tf2#3]
What I mean is why not keep it all into one parent folder which has sub folders like esp, Attack/Weapons etc

 -> Movement
Features -> Weapons
-> Visuals

However I find it confusing how there is a folder called client which has the movement, stabbing etc but another folder called Features with only the esp.

I've just started wanting to get into cheat development so excuse me for me not understanding even though it may be obvious.

**Comment by emilyinure** [comment]
The separation of visuals and the other features was from my friends base being updated while i was still working on this, and then having a conflict. I've fixed the project hierarchy/filters. Hope you have fun working on it

**Comment by LocalSmail** [comment]
> The separation of visuals and the other features was from my friends base being updated while i was still working on this, and then having a conflict. I've fixed the project hierarchy/filters. Hope you have fun working on it

Got you. Thanks.
