### ISSUE TITLE
Please make the binds more clear/as regular (i said it before but horribly)

### ISSUE THREAD

**Issue by FedUser23** [emilyinure/haven-tf2#32]
i do not understand the bind system sometimes it fires properly sometimes it doesn't which is the one where it is hold to shoot????

**Comment by emilyinure** [comment]
Set your bind to the key you want to use, right click the bind button and set it to "Hold"

Afterward select the firing mode, if you want to control the firing manually and only have it aim for you, select "Default"
If you want to automatically release the attack key(mainly for charge weapons) select "Automatic release"
If you want it to automatically shoot, and charge weapons, select "Automatic"
